[pytest]
python_files = test_*.py
python_functions = test_*
#pytest_files = *test.py
#markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции
#pytest_functions = test_sum_positive_nums
